server:
  port: 8080
spring:
  application:
    name: TTMS
  datasource:
    url: jdbc:mysql://114.115.204.56:3306/ttms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345a
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 114.115.204.56
    password: 123wan12345
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    default-property-inclusion: non_null
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
  - 114.115.204.56:22122
ttms:
  upload:
    baseUrl: http://114.115.204.56
    maxsize: 1
    unit: M
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
